version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apollon-superadmin-panel-container
    restart: always
    working_dir: /app
    ports:
      - '${APP_PORT}:80'
    env_file:
      - .env